### ISSUE TITLE
Create `Image Slider` Section

### ISSUE THREAD

**Issue by su1nta** [su1nta/Apple_In_Clone#1]
### About the task

- The main www.apple.com/in has an image slider in the bottom half of the homepage, above the footer section featuring the Apple TV+ shows.
- As this project is a clone of the main website, the slider is needed to be as much accurate as possible to the original slider.
- vanilla JavaScript is recommended to use.
![image-slider-apple-india](https://user-images.githubusercontent.com/62897008/195017905-1a5d57d8-035f-4a16-abc5-416d58a4dbbe.png)

**Comment by Aman0786-git** [comment]
Can you assign it to me

**Comment by su1nta** [comment]
@Aman0786-git Okay, you can start working on it. Thanks for showing interest in this repo.

**Comment by su1nta** [comment]
@Aman0786-git It's been 3 days, have you started working on issue #1?

**Comment by su1nta** [comment]
@Aman0786-git Since I have not gotten a response from you in days, I have to unassign you from this issue.

**Comment by priyanshumaitra** [comment]
@su1nta Delete this issue and re-open. The chances of getting responses are much quicker.

**Comment by su1nta** [comment]
@priyanshumaitra Okay, thanks for the advise.
