### ISSUE TITLE
Update the Banners in Homepage

### ISSUE THREAD

**Issue by su1nta** [su1nta/Apple_In_Clone#4]
The development of the site was started before the iPhone 14 and Apple Watch launch, and the banners have been changed in the official site after the launches occurred. 
This is what the clone looks like: 

https://user-images.githubusercontent.com/62897008/195386953-b722252b-5973-4b95-b7f2-95e991a96623.mp4

And this is what the [official site](https://www.apple.com/in/) looks like:

https://user-images.githubusercontent.com/62897008/195387195-4a55870a-9b7c-4248-b515-5c21559d88d7.mp4

So, the site needs to be updated with new images and headings. And as it is a clone, all banners should be accurate to the actual banners.

**Comment by HyperWoo** [comment]
Sir, I would love to contribute, can you assign this issue to me?

**Comment by su1nta** [comment]
@HyperWoo you can start working on it, your PR will be merged if the issue is resolved properly.

**Comment by HyperWoo** [comment]
@su1nta Greetings sir, I have Cloned the banner and the banner's first image of the website with precision. 

- may I create a PR for this action?


![Screenshot (819)](https://user-images.githubusercontent.com/114022709/195560015-1bbcf954-8633-433c-9644-d60a8cfdac19.png)
 **Clone**



![Screenshot (820)](https://user-images.githubusercontent.com/114022709/195560025-f6056d07-3d00-4d4a-b5e7-ee69e5de4922.png)
**Actual**

**Comment by su1nta** [comment]
@HyperWoo  **Correction:** Use a bit narrower font in the product tag-line(like "Big and bigger" in iPhone 14 banner). Otherwise everything seems good.
Complete all the banners then make a pr.
_Happy Hacktoberfest:)_
