### ISSUE TITLE
Create a README file

### ISSUE THREAD

**Issue by su1nta** [su1nta/Apple_In_Clone#5]
A Readme file is needed with proper documentation so beginners can also contribute in this repo.
The **README** file should include :

- What is this Repository or project about
- What Technologies are used
- How to Contribute in this Repo(e.g. how to fork, clone, create separate branch etc. )

**Comment by DakshVarshney1409** [comment]
I would like to contribute. @su1nta

**Comment by su1nta** [comment]
Okay @DakshVarshney1409 , you can start working on it.

**Comment by jayantchaudhari18** [comment]
Hey @su1nta  can you assign this task to me.

**Comment by su1nta** [comment]
@jayantchaudhari18, this issue is already resolved by @DakshVarshney1409 . Thank you for showing interest in this repo.
